Implement KNNRegressor
dmarjanovic94/4-ml-siit-2017 pull request #2
Opened 2017-04-06 19:00 UTC by bojanbla

Summary:

- Implement multi variable linear regression using **KNN classifier**
- Short description added in **README.md**

2017-04-06 22:36 UTC, drmarjanovic requested changes

2017-04-06 22:36 UTC, drmarjanovic commented on ex-02-multi-var-lin-reg/knn_regressor.py
> +        return sqrt(distance)
You can use **map** with **zip** here.

2017-04-06 22:36 UTC, drmarjanovic commented on ex-02-multi-var-lin-reg/knn_regressor.py
> +            distance += abs(x[i] - y[i])
Also, you can use **map** and **zip** here. 😄

2017-04-06 22:36 UTC, drmarjanovic commented on ex-02-multi-var-lin-reg/test.py
> +    df = pd.read_csv('data/train.csv')
Use more clear name for variables. What does this mean? 😄

2017-04-06 22:36 UTC, drmarjanovic commented on ex-02-multi-var-lin-reg/test.py
> +
I'm not sure that we now need to split data. Validation set will be provided from his side. Maybe, you can make additional parameter in **args** for this. Maybe we should use all this provided data for training.

2017-04-07 23:55 UTC, stkeky commented on ex-02-multi-var-lin-reg/test.py
> +    df = pd.read_csv('data/train.csv')
`df` is 'standard' short-name for `pandas.DataFrame` so it's not that bad 😃

2017-04-07 23:55 UTC, stkeky commented on ex-02-multi-var-lin-reg/knn_regressor.py
> +        return sqrt(distance)
Change was made to use `map` and `reduce`.

2017-04-07 23:56 UTC, stkeky commented on ex-02-multi-var-lin-reg/knn_regressor.py
> +            distance += abs(x[i] - y[i])
Change was made to use `map` and `reduce`.

2017-04-07 23:58 UTC, stkeky commented
I added 2 more fields (`internet` & `guardian`) which only in this combination gives **`validation_rmse = 2.28`** and **`test_rmse = 2.76`**.

 _RMSEs were **2.43** and **2.91** respectfully._

2017-04-08 00:01 UTC, stkeky commented on ex-02-multi-var-lin-reg/test.py
> +
I agree, TA provided separate `*.csv` files.

2017-04-09 20:34 UTC, drmarjanovic approved these changes

2017-04-09 20:34 UTC, merged